### ISSUE TITLE
Build error: 

### ISSUE THREAD

**Issue by jingweiz** [Xamla/torch-pcl#10]
Hi,
I'm trying to install this package with: 
`luarocks install --server=http://luarocks.org/dev torch-pcl`
(I tried with `luarocks install pcl` but get "Error: No results matching query were found.")

but get this error:

In file included from /tmp/luarocks_torch-pcl-scm-1-1014/torch-pcl/src/generic.cpp:2:0,
                 from /tmp/luarocks_torch-pcl-scm-1-1014/torch-pcl/src/xyz.cpp:4:
/tmp/luarocks_torch-pcl-scm-1-1014/torch-pcl/src/generic/io.cpp: In function ‘int pcl_PointCloud_XYZ_loadOBJFile(pcl::PointCloudpcl::PointXYZ::Ptr_, const char_)’:
/tmp/luarocks_torch-pcl-scm-1-1014/torch-pcl/src/generic/io.cpp:30:12: error: ‘loadOBJFile’ is not a member of ‘pcl::io’
     return pcl::io::loadOBJFile(fn, *_self);
            ^
make[2]: *_\* [CMakeFiles/pcl.dir/src/xyz.cpp.o] Error 1
make[1]: **\* [CMakeFiles/pcl.dir/all] Error 2
make: **\* [all] Error 2

Error: Build error: Failed building.

Can you help me with this issue? Thanks a lot!

**Comment by andreaskoepf** [comment]
torch-pcl requires pcl-1.8. If it is not installed on your machine please consider getting the head version of the pcl and build form source.

**Comment by jingweiz** [comment]
Ah thanks a lot! It works:)
