### ISSUE TITLE
Error: No results matching query were found

### ISSUE THREAD

**Issue by antonmil** [Xamla/torch-pcl#9]
Hi,

I'm getting the above message when I try to install the package with `luarocks install pcl`. Any ideas? I have Torch7 and PCL installed.

**Comment by andreaskoepf** [comment]
@antonmil The luarocks package name is 'torch-pcl' .. but you can also simply use `git clone https://github.com/Xamla/torch-pcl.git` and then run `luarock make rocks/torch-pcl-scm-1.rockspec` from within the `torch-pcl` directory.

**Comment by antonmil** [comment]
Great, thanks!
